In [9]:
import pandas as pd

In [10]:
columns = ["hit_rate@1", "hit_rate@5", "hit_rate@10", "hits@1", "hits@5", "hits@10", 
										 "precision@1", "precision@5", "precision@10", "recall@1", "recall@5", 
										 "recall@10", "f1@1", "f1@5", "f1@10", "mrr"]
EN_index = ['Voyage EN Easy', 'Voyage EN Hard', 'AllMini EN Easy' , 'AllMini EN Hard']
ML_index = ['Voyage ML Easy', 'Voyage ML Hard', 'LaBSE ML Easy' , 'LaBSE ML Hard']

## result load

### multilingual

In [11]:
# voyage results
voyage_ml_res_e = {'hit_rate@1': 0.44234423442344234,
 'hit_rate@5': 0.7103710371037104,
 'hit_rate@10': 0.7972797279727972,
 'hits@1': 0.44234423442344234,
 'hits@5': 1.7843784378437844,
 'hits@10': 2.8171817181718173,
 'precision@1': 0.44234423442344234,
 'precision@5': 0.35687568756875687,
 'precision@10': 0.2817181718171817,
 'recall@1': 0.025777440277514607,
 'recall@5': 0.10275383562363946,
 'recall@10': 0.1598003330409256,
 'f1@1': 0.048516616948872646,
 'f1@5': 0.15714077208635488,
 'f1@10': 0.1993778592977252,
 'mrr': 0.5551005100510051}

voyage_ml_res_h = {'hit_rate@1': 0.3562,
 'hit_rate@5': 0.5856,
 'hit_rate@10': 0.6746,
 'hits@1': 0.3562,
 'hits@5': 1.3276,
 'hits@10': 2.0942,
 'precision@1': 0.3562,
 'precision@5': 0.26552,
 'precision@10': 0.20942,
 'recall@1': 0.01894839338855732,
 'recall@5': 0.06895079136511777,
 'recall@10': 0.10598128450763515,
 'f1@1': 0.03564375441614217,
 'f1@5': 0.10598975419345513,
 'f1@10': 0.13453166405276384,
 'mrr': 0.4537818253968254}

labse_ml_res_e = {'hit_rate@1': 0.3941394139413941,
 'hit_rate@5': 0.6242624262426243,
 'hit_rate@10': 0.6925692569256926,
 'hits@1': 0.3941394139413941,
 'hits@5': 1.4577457745774578,
 'hits@10': 2.141314131413141,
 'precision@1': 0.3941394139413941,
 'precision@5': 0.2915491549154916,
 'precision@10': 0.21413141314131418,
 'recall@1': 0.022864639476532615,
 'recall@5': 0.08319318718281847,
 'recall@10': 0.12000520579114711,
 'f1@1': 0.04304394791689301,
 'f1@5': 0.1274429922009638,
 'f1@10': 0.1502583571973859,
 'mrr': 0.49147097249407484}

labse_ml_res_h = {'hit_rate@1': 0.2962,
 'hit_rate@5': 0.4728,
 'hit_rate@10': 0.534,
 'hits@1': 0.2962,
 'hits@5': 0.983,
 'hits@10': 1.4256,
 'precision@1': 0.2962,
 'precision@5': 0.1966,
 'precision@10': 0.14256,
 'recall@1': 0.015755643717248104,
 'recall@5': 0.050601642253226546,
 'recall@10': 0.07155153062651759,
 'f1@1': 0.029644910301610827,
 'f1@5': 0.077953109222548,
 'f1@10': 0.09110383014838688,
 'mrr': 0.3707429365079365}

### english

In [12]:
# voyage : 
voyage_en_res_e = {'hit_rate@1': 0.4383,
 'hit_rate@5': 0.7212,
 'hit_rate@10': 0.8151,
 'hits@1': 0.4383,
 'hits@5': 1.8119,
 'hits@10': 2.9827,
 'precision@1': 0.4383,
 'precision@5': 0.36238000000000004,
 'precision@10': 0.29827,
 'recall@1': 0.025954274709414686,
 'recall@5': 0.10613667485105341,
 'recall@10': 0.17228924063579848,
 'f1@1': 0.0488169223588933,
 'f1@5': 0.16188768040450505,
 'f1@10': 0.21393279419299424,
 'mrr': 0.5581295634920634}

voyage_en_res_h = {'hit_rate@1': 0.3924,
 'hit_rate@5': 0.642,
 'hit_rate@10': 0.7324,
 'hits@1': 0.3924,
 'hits@5': 1.3678,
 'hits@10': 2.1248,
 'precision@1': 0.3924,
 'precision@5': 0.27355999999999997,
 'precision@10': 0.21248000000000003,
 'recall@1': 0.024297473867399548,
 'recall@5': 0.08218130866717278,
 'recall@10': 0.12448558778996978,
 'f1@1': 0.04530712952713923,
 'f1@5': 0.12251631795880387,
 'f1@10': 0.15054019529388152,
 'mrr': 0.4973300793650793}

allmini_en_res_e = {'hit_rate@1': 0.4205,
 'hit_rate@5': 0.6875,
 'hit_rate@10': 0.7733,
 'hits@1': 0.4205,
 'hits@5': 1.6818,
 'hits@10': 2.6592,
 'precision@1': 0.4205,
 'precision@5': 0.33636000000000005,
 'precision@10': 0.26592000000000005,
 'recall@1': 0.024898180288386494,
 'recall@5': 0.09855823220650244,
 'recall@10': 0.15367572830522128,
 'f1@1': 0.046832434298041396,
 'f1@5': 0.15033559576651387,
 'f1@10': 0.19083342065914094,
 'mrr': 0.5338618650793651}

allmini_en_res_h = {'hit_rate@1': 0.3636,
 'hit_rate@5': 0.5816,
 'hit_rate@10': 0.6674,
 'hits@1': 0.3636,
 'hits@5': 1.2068,
 'hits@10': 1.811,
 'precision@1': 0.3636,
 'precision@5': 0.24136000000000005,
 'precision@10': 0.1811,
 'recall@1': 0.02247661122301701,
 'recall@5': 0.07208252938471876,
 'recall@10': 0.10578481888152237,
 'f1@1': 0.041905091997086336,
 'f1@5': 0.1075887627242425,
 'f1@10': 0.1280440510235222,
 'mrr': 0.4569129365079365}

## table

In [13]:
# voyage_en_res_e, voyage_en_res_h, allmini_en_res_e, allmini_en_res_h
# voyage_ml_res_e ,voyage_ml_res_h , labse_ml_res_e , labse_ml_res_h
en_values = [list(voyage_en_res_e.values()), list(voyage_en_res_h.values()),
 list(allmini_en_res_e.values()), list(allmini_en_res_h.values())]

ml_values = [list(voyage_ml_res_e.values()), list(voyage_ml_res_h.values()),
 list(labse_ml_res_e.values()), list(labse_ml_res_h.values())]

In [14]:
en_results_df = pd.DataFrame(en_values, index = EN_index , columns = columns)
ml_results_df = pd.DataFrame(ml_values, index= ML_index , columns = columns )

In [21]:
for x in en_results_df.columns.tolist():
    print(x , end = ' | ' )

hit_rate@1 | hit_rate@5 | hit_rate@10 | hits@1 | hits@5 | hits@10 | precision@1 | precision@5 | precision@10 | recall@1 | recall@5 | recall@10 | f1@1 | f1@5 | f1@10 | mrr |

In [15]:
en_results_df

,hit_rate@1,hit_rate@5,hit_rate@10,hits@1,hits@5,hits@10,precision@1,precision@5,precision@10,recall@1,recall@5,recall@10,f1@1,f1@5,f1@10,mrr
Voyage EN Easy,0.4383,0.7212,0.8151,0.4383,1.8119,2.9827,0.4383,0.36238,0.29827,0.025954,0.106137,0.172289,0.048817,0.161888,0.213933,0.558130
Voyage EN Hard,0.3924,0.6420,0.7324,0.3924,1.3678,2.1248,0.3924,0.27356,0.21248,0.024297,0.082181,0.124486,0.045307,0.122516,0.150540,0.497330
AllMini EN Easy,0.4205,0.6875,0.7733,0.4205,1.6818,2.6592,0.4205,0.33636,0.26592,0.024898,0.098558,0.153676,0.046832,0.150336,0.190833,0.533862
AllMini EN Hard,0.3636,0.5816,0.6674,0.3636,1.2068,1.8110,0.3636,0.24136,0.18110,0.022477,0.072083,0.105785,0.041905,0.107589,0.128044,0.456913

In [16]:
ml_results_df

,hit_rate@1,hit_rate@5,hit_rate@10,hits@1,hits@5,hits@10,precision@1,precision@5,precision@10,recall@1,recall@5,recall@10,f1@1,f1@5,f1@10,mrr
Voyage ML Easy,0.442344,0.710371,0.797280,0.442344,1.784378,2.817182,0.442344,0.356876,0.281718,0.025777,0.102754,0.159800,0.048517,0.157141,0.199378,0.555101
Voyage ML Hard,0.356200,0.585600,0.674600,0.356200,1.327600,2.094200,0.356200,0.265520,0.209420,0.018948,0.068951,0.105981,0.035644,0.105990,0.134532,0.453782
LaBSE ML Easy,0.394139,0.624262,0.692569,0.394139,1.457746,2.141314,0.394139,0.291549,0.214131,0.022865,0.083193,0.120005,0.043044,0.127443,0.150258,0.491471
LaBSE ML Hard,0.296200,0.472800,0.534000,0.296200,0.983000,1.425600,0.296200,0.196600,0.142560,0.015756,0.050602,0.071552,0.029645,0.077953,0.091104,0.370743